### ISSUE TITLE
Clean up: Try / Catch statements returning errors which are mistaken for other objects

### ISSUE THREAD

**Issue by emaG3m** [near/near-web3-provider#28]
Finding errors in here can be really tough sometimes, because of try / catch statements returning errors. The receiving code is expecting this to be the success object and tries to execute functions on the error, leading to really confusing and nonhelpful stacktraces/errors.

**Comment by emaG3m** [comment]
Also, try/catch in beforeAll statements keep running subsequent tests instead of halting at the beforeAll. Thinking we might not need these?

**Comment by barbaraliau** [comment]
> Also, try/catch in beforeAll statements keep running subsequent tests instead of halting at the beforeAll. Thinking we might not need to catch beforeAll errors?

I had thought that an error in `beforeAll` would prevent further tests from happening, but apparently it does not because you might want to test what happens if that stuff fails. We'll need to rewrite the structure of the tests if we want that behavior.

**Comment by barbaraliau** [comment]
Bailing on the first test failure is what will happen in Mocha and Jasmine, but it does not function the same in Jest. https://github.com/facebook/jest/issues/2867

**Comment by emaG3m** [comment]
ok. I noticed if you take out some (of the non-test) try/catch statements, errors can hang for up to 30 seconds, which is annoying. I think the quickest fix is to at least console.log errors so the actual error will come up in the terminal

**Comment by barbaraliau** [comment]
Yeah that sounds good. Wherever there is an async function, catching and logging the error at minimum is usually the best to prevent long hangs.

**Comment by emaG3m** [comment]
fix merged!!!!! ---^
