### ISSUE TITLE
Translate logs

### ISSUE THREAD

**Issue by prestwich** [near/near-web3-provider#3]
In `near_to_eth_objects.js` we should have `transactionReceiptObj` translate near logs to the eth log format.

```
{
    "logIndex": "0x1", // 1
    "blockNumber":"0x1b4", // 436
    "blockHash": "0x8216c5785ac562ff41e2dcfdf5785ac562ff41e2dcfdf829c5a142f1fccd7d",
    "transactionHash":  "0xdf829c5a142f1fccd7d8216c5785ac562ff41e2dcfdf5785ac562ff41e2dcf",
    "transactionIndex": "0x0", // 0
    "address": "0x16c5785ac562ff41e2dcfdf829c5a142f1fccd7d",
    "data":"0x0000000000000000000000000000000000000000000000000000000000000000",
    "topics": ["0x59ebeb90bc63057b6515673c3ecf9438e5058bca0f92585014eced636878c9a5"]
}
```

**Comment by emaG3m** [comment]
Are we even getting any evm log information back from the Near provider? Confused about the scope of this issue.

**Comment by barbaraliau** [comment]
@emaG3m Was this resolved when #11 was closed out?

**Comment by emaG3m** [comment]
> @emaG3m Was this resolved when #11 was closed out?

thanks, meant to notate this here. I believe that draft PR started the work on this here:
https://github.com/nearprotocol/near-web3-provider/pull/11/files#diff-6b7c2bc4d2eaf8279b65a551cf61a6acR279

this hasn't been merged though. so this remains unresolved.

**Comment by emaG3m** [comment]
actually I will need clarification on this. are we getting any ethereum logs back somehow? This is an array, but of which items are we translating for this array?

**Comment by prestwich** [comment]
I think this was resolved (more or less) on a branch that was never merged

https://github.com/nearprotocol/near-web3-provider/blob/evm-bug-demo-plus-fixes/src/near_to_eth_objects.js#L289-L308

**Comment by emaG3m** [comment]
cool. I think we just don't have hardly any logs right now which is why i was having trouble finding them. will make more.

**Comment by emaG3m** [comment]
fixed!
